In [155]:
import pandas as pd

In [156]:
import numpy as np

In [157]:
def create_data(IV):
    return IV * 2 + (np.random.randint(0,10))/10

In [158]:
create_data(1)

2.6

In [159]:
create_data(25)

50.5

In [160]:
df = []

In [161]:
counter = 0
while counter < 1000:
    value = {}
    value['IV'] = np.random.randint(0,100)
    df.append(value)
    counter += 1

In [162]:
df[:10]

[{'IV': 85},
 {'IV': 22},
 {'IV': 37},
 {'IV': 73},
 {'IV': 78},
 {'IV': 71},
 {'IV': 37},
 {'IV': 98},
 {'IV': 23},
 {'IV': 77}]

In [163]:
df = pd.DataFrame(df)

In [164]:
df

IV
0    85
1    22
2    37
3    73
4    78
..   ..
995   6
996  86
997  33
998  29
999  24

[1000 rows x 1 columns]

In [165]:
df.describe()

IV
count  1000.000000
mean     50.028000
std      28.833637
min       0.000000
25%      24.000000
50%      52.000000
75%      75.000000
max      99.000000

In [166]:
df['DV'] = df['IV'].apply(create_data)

In [167]:
df

IV     DV
0    85  170.2
1    22   44.0
2    37   74.8
3    73  146.0
4    78  156.7
..   ..    ...
995   6   12.5
996  86  172.3
997  33   66.1
998  29   58.5
999  24   48.9

[1000 rows x 2 columns]

In [168]:
df.describe()

IV           DV
count  1000.000000  1000.000000
mean     50.028000   100.503800
std      28.833637    57.680255
min       0.000000     0.000000
25%      24.000000    48.900000
50%      52.000000   104.500000
75%      75.000000   150.475000
max      99.000000   198.900000

## Using sklearn to train a model and make predictions

In [169]:
from sklearn.linear_model import LinearRegression

Instantiating the model

In [170]:
reg = LinearRegression()

In [171]:
reg

LinearRegression()

Fitting the model with training data

In [172]:
reg.fit(df[['IV']], df['DV'])

LinearRegression()

In [173]:
df[['IV']]

IV
0    85
1    22
2    37
3    73
4    78
..   ..
995   6
996  86
997  33
998  29
999  24

[1000 rows x 1 columns]

In [174]:
df['DV']

0      170.2
1       44.0
2       74.8
3      146.0
4      156.7
       ...  
995     12.5
996    172.3
997     66.1
998     58.5
999     48.9
Name: DV, Length: 1000, dtype: float64

In [175]:
reg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

Getting the coefficient(s)

In [176]:
reg.coef_

array([2.00042413])

Making predictions

In [177]:
reg.predict([[1]])

array([2.42700566])

In [178]:
reg.predict([[100]])

array([200.46899472])

In [179]:
reg.predict([[50]])

array([100.44778812])

In [180]:
df['IV'].max()

99

In [181]:
reg.predict([[1000]])

array([2000.85071347])

## Statistical testing

In [182]:
import statsmodels.api as sm

In [183]:
Y = df['DV']
X = df['IV']

In [184]:
X = sm.add_constant(X)

In [185]:
model = sm.OLS(Y,X)

In [186]:
results = model.fit()

In [187]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     DV   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.823e+07
Date:                Fri, 02 Jul 2021   Prob (F-statistic):               0.00
Time:                        17:36:35   Log-Likelihood:                -196.67
No. Observations:                1000   AIC:                             397.3
Df Residuals:                     998   BIC:                             407.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4266      0.019     22.837      0.000       0.390       0.463
IV             2.0004      0.000   6182.944      0.000       2.000       2.001
==============================================================================
Omnibus:                     1420.303   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               67.157
Skew:                           0.019   Prob(JB):                     2.61e-15
Kurtosis:                       1.731   Cond. No.                         116.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Using the Google Analytics Dataset
(Modified for Digital Analytics)

In [188]:
data = pd.read_csv('~/OneDrive - UvA/DigitalSociety/TeachTheTeacher-Python/TeachTheTeacherPython-Datasets/googlestore_DA5weeklychallenges.csv')

/Users/t.b.araujouva.nl/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (1,3,7,9,19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [189]:
data.head()

Unnamed: 0 affiliate channelGrouping cpc        date    device_browser  \
0         0.0         0        Referral   0  20171001.0            Chrome   
1         1.0         0     Paid Search   1  20171001.0            Chrome   
2         2.0         0         Display   1  20171001.0            Chrome   
3         3.0         0         Display   1  20171001.0  Samsung Internet   
4         4.0         0         Display   1  20171001.0            Safari   

  device_deviceCategory device_isMobile device_operatingSystem  \
0               desktop           False              Macintosh   
1               desktop           False              Macintosh   
2                mobile            True                Android   
3                mobile            True                Android   
4                mobile            True                    iOS   

         fullVisitorId  ... trafficSource_adwordsClickInfo_slot  \
0  9460190543836614586  ...                                 NaN   
1  1480173241963500874  ...                                 Top   
2  2873420789599649821  ...                                 RHS   
3   958777956895332252  ...                                 RHS   
4  3000721821736270436  ...                                 RHS   

                              trafficSource_campaign  \
0                                          (not set)   
1                 AW - Dynamic Search Ads Whole Site   
2  1000557 | GA | US | en | Hybrid | GDN Remarketing   
3  1000557 | GA | US | en | Hybrid | GDN Remarketing   
4  1000557 | GA | US | en | Hybrid | GDN Remarketing   

  trafficSource_isTrueDirect trafficSource_keyword trafficSource_medium  \
0                        NaN                   NaN               (none)   
1                        NaN      6qEhsCssdK0z36ri                  cpc   
2                        NaN  (automatic matching)                  cpc   
3                        NaN  (automatic matching)                  cpc   
4                        NaN  (automatic matching)                  cpc   

  trafficSource_referralPath trafficSource_source       visitId visitNumber  \
0                          /             (direct)  1.506841e+09         1.0   
1                        NaN               google  1.506841e+09         1.0   
2                        NaN               google  1.506841e+09         1.0   
3                        NaN               google  1.506841e+09         1.0   
4                        NaN               google  1.506841e+09         1.0   

  visitStartTime  
0   1.506841e+09  
1   1.506841e+09  
2   1.506841e+09  
3   1.506841e+09  
4   1.506841e+09  

[5 rows x 80 columns]

In [190]:
data.columns

Index(['Unnamed: 0', 'affiliate', 'channelGrouping', 'cpc', 'date',
       'device_browser', 'device_deviceCategory', 'device_isMobile',
       'device_operatingSystem', 'fullVisitorId', 'geoNetwork_city',
       'geoNetwork_continent', 'geoNetwork_country', 'geoNetwork_metro',
       'geoNetwork_networkDomain', 'geoNetwork_region',
       'geoNetwork_subContinent', 'isExit',
       'landing_appInfo_landingScreenName', 'landing_appInfo_screenDepth',
       'landing_appInfo_screenName', 'landing_contentGroup_contentGroup1',
       'landing_contentGroup_contentGroup2',
       'landing_contentGroup_contentGroup3',
       'landing_contentGroup_contentGroup4',
       'landing_contentGroup_contentGroup5', 'landing_hour',
       'landing_isEntrance', 'landing_isExit', 'landing_minute',
       'landing_page_hostname', 'landing_page_pagePath',
       'landing_page_pagePathLevel1', 'landing_page_pagePathLevel2',
       'landing_page_pagePathLevel3', 'landing_page_pagePathLevel4',
       'landing

In [191]:
data['order_euros']

0        616.0
1          NaN
2          NaN
3        980.0
4        497.0
         ...  
52305    977.0
52306    240.0
52307    764.0
52308      NaN
52309    990.0
Name: order_euros, Length: 52310, dtype: float64

In [192]:
data[['channelGrouping', 'device_browser', 'order_euros']].describe()

order_euros
count  28815.000000
mean     412.265279
std      312.846197
min        1.000000
25%      131.000000
50%      336.000000
75%      691.000000
max      999.000000

In [193]:
data[['channelGrouping', 'device_browser', 'order_euros']].dtypes

channelGrouping     object
device_browser      object
order_euros        float64
dtype: object

In [194]:
data[['channelGrouping', 'device_browser', 'order_euros']].isna().sum()

channelGrouping        0
device_browser         0
order_euros        23495
dtype: int64

In [195]:
data['channelGrouping'].value_counts()

Organic Search    22781
Display           12579
Direct             6047
Referral           4994
Social             3828
Paid Search        1322
Affiliates          756
 :                    2
(Other)               1
Name: channelGrouping, dtype: int64

In [196]:
data['device_browser'].value_counts()

Chrome                        34324
Safari                         8883
Samsung Internet               3100
Android Webview                1783
Firefox                        1693
Internet Explorer               780
Opera Mini                      484
Edge                            432
Opera                           261
UC Browser                      220
Safari (in-app)                 141
Amazon Silk                      71
YaBrowser                        37
Android Browser                  35
Coc Coc                          15
Puffin                           13
Mozilla Compatible Agent         10
BlackBerry                        7
Maxthon                           7
1                                 2
osee2unifiedRelease               2
tfowdqmibyshaklxuregpcnzvj        1
ujvrzsonxihlgaqdmkwtbfcpey        1
wfpknuqxovyilmrdzbhgtecjas        1
(not set)                         1
Browser                           1
ecgiwapzltrkujdhmqsbxfonvy        1
Nintendo Browser            

In [197]:
data['order_euros'].describe()

count    28815.000000
mean       412.265279
std        312.846197
min          1.000000
25%        131.000000
50%        336.000000
75%        691.000000
max        999.000000
Name: order_euros, dtype: float64

In [198]:
data['order_euros_complete'] = data['order_euros'].fillna(0)

In [199]:
data['order_euros_complete'].describe()

count    52310.000000
mean       227.096616
std        309.781227
min          0.000000
25%          0.000000
50%         42.000000
75%        391.000000
max        999.000000
Name: order_euros_complete, dtype: float64

In [200]:
data['order_euros_complete'].isna().sum()

0

In [201]:
def is_organic_search(text):
    if text == 'Organic Search':
        return 1
    return 0

In [202]:
data['org_search'] = data['channelGrouping'].apply(is_organic_search)

In [203]:
data['org_search'].value_counts()

0    29529
1    22781
Name: org_search, dtype: int64

In [204]:
def is_chrome(text):
    if 'Chrome' in text:
        return 1
    else:
        return 0

In [205]:
data['chrome'] = data['device_browser'].apply(is_chrome)

In [206]:
data['chrome'].value_counts()

1    34324
0    17986
Name: chrome, dtype: int64

In [207]:
data['chrome']

0        1
1        1
2        1
3        0
4        0
        ..
52305    1
52306    1
52307    1
52308    1
52309    0
Name: chrome, Length: 52310, dtype: int64

In [208]:
data[['chrome', 'org_search', 'order_euros_complete']]

chrome  org_search  order_euros_complete
0           1           0                 616.0
1           1           0                   0.0
2           1           0                   0.0
3           0           0                 980.0
4           0           0                 497.0
...       ...         ...                   ...
52305       1           0                 977.0
52306       1           1                 240.0
52307       1           0                 764.0
52308       1           1                   0.0
52309       0           0                 990.0

[52310 rows x 3 columns]

In [209]:
data[['chrome', 'org_search', 'order_euros_complete']].describe()

chrome    org_search  order_euros_complete
count  52310.000000  52310.000000          52310.000000
mean       0.656165      0.435500            227.096616
std        0.474991      0.495827            309.781227
min        0.000000      0.000000              0.000000
25%        0.000000      0.000000              0.000000
50%        1.000000      0.000000             42.000000
75%        1.000000      1.000000            391.000000
max        1.000000      1.000000            999.000000

In [210]:
data[['chrome', 'org_search', 'order_euros_complete']].isna().sum()

chrome                  0
org_search              0
order_euros_complete    0
dtype: int64

In [211]:
features = ['chrome', 'org_search']

In [212]:
features

['chrome', 'org_search']

In [213]:
import statsmodels.api as sm

In [214]:
X = sm.add_constant(data[features])

In [215]:
model_euros = sm.OLS(data['order_euros_complete'], X)

In [216]:
results_model_euros = model_euros.fit()

In [217]:
results_model_euros.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results                             
================================================================================
Dep. Variable:     order_euros_complete   R-squared:                       0.133
Model:                              OLS   Adj. R-squared:                  0.133
Method:                   Least Squares   F-statistic:                     4023.
Date:                  Fri, 02 Jul 2021   Prob (F-statistic):               0.00
Time:                          17:36:42   Log-Likelihood:            -3.7052e+05
No. Observations:                 52310   AIC:                         7.411e+05
Df Residuals:                     52307   BIC:                         7.411e+05
Df Model:                             2                                         
Covariance Type:              nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        349.1769      2.406    145.108      0.000     344.461     353.893
chrome       -36.8375      2.655    -13.874      0.000     -42.041     -31.634
org_search  -224.8195      2.543    -88.390      0.000    -229.805    -219.834
==============================================================================
Omnibus:                     4605.359   Durbin-Watson:                   1.967
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5183.579
Skew:                           0.736   Prob(JB):                         0.00
Kurtosis:                       2.542   Cond. No.                         3.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [218]:
from sklearn.linear_model import LinearRegression

In [219]:
reg_order_euros = LinearRegression()

In [220]:
reg_order_euros.fit(data[features], data['order_euros_complete'])

LinearRegression()

In [221]:
reg_order_euros.coef_

array([ -36.83747443, -224.81947091])

In [222]:
reg_order_euros.predict([[1,1]])

array([87.51999672])

In [223]:
reg_order_euros.predict([[0,0]])

array([349.17694206])

In [224]:
reg_order_euros.predict([[1,0]])

array([312.33946763])

In [225]:
reg_order_euros.predict([[0,1]])

array([124.35747115])

# Moving to categorical targets

* Independent variable = feature
* Dependent variable = target or label

In [226]:
data['order_euros_complete'].describe()

count    52310.000000
mean       227.096616
std        309.781227
min          0.000000
25%          0.000000
50%         42.000000
75%        391.000000
max        999.000000
Name: order_euros_complete, dtype: float64

In [227]:
def purchased(order):
    if order == 0:
        return 0
    return 1

In [228]:
data['purchase'] = data['order_euros_complete'].apply(purchased)

In [229]:
data['purchase'].describe()

count    52310.000000
mean         0.550851
std          0.497412
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: purchase, dtype: float64

In [230]:
data['purchase'].value_counts()

1    28815
0    23495
Name: purchase, dtype: int64

In [231]:
features

['chrome', 'org_search']

In [232]:
from sklearn.linear_model import LogisticRegression

In [233]:
clf_lr = LogisticRegression(random_state=0)

In [234]:
clf_lr

LogisticRegression(random_state=0)

In [235]:
clf_lr.fit(data[features], data['purchase'])

LogisticRegression(random_state=0)

In [236]:
clf_lr.predict([[0,0]])

array([1])

In [237]:
clf_lr.predict([[0,1]])

array([1])

In [238]:
clf_lr.predict([[1,1]])

array([0])

In [239]:
clf_lr.predict([[1,0]])

array([1])

In [240]:
clf_lr.predict_proba([[0,0]])

array([[0.3966664, 0.6033336]])

In [241]:
clf_lr.predict_proba([[0,1]])

array([[0.49025323, 0.50974677]])

In [242]:
clf_lr.predict_proba([[1,0]])

array([[0.41424883, 0.58575117]])

In [243]:
clf_lr.predict_proba([[1,1]])

array([[0.50848778, 0.49151222]])

In [244]:
data.head()

Unnamed: 0 affiliate channelGrouping cpc        date    device_browser  \
0         0.0         0        Referral   0  20171001.0            Chrome   
1         1.0         0     Paid Search   1  20171001.0            Chrome   
2         2.0         0         Display   1  20171001.0            Chrome   
3         3.0         0         Display   1  20171001.0  Samsung Internet   
4         4.0         0         Display   1  20171001.0            Safari   

  device_deviceCategory device_isMobile device_operatingSystem  \
0               desktop           False              Macintosh   
1               desktop           False              Macintosh   
2                mobile            True                Android   
3                mobile            True                Android   
4                mobile            True                    iOS   

         fullVisitorId  ... trafficSource_medium trafficSource_referralPath  \
0  9460190543836614586  ...               (none)                          /   
1  1480173241963500874  ...                  cpc                        NaN   
2  2873420789599649821  ...                  cpc                        NaN   
3   958777956895332252  ...                  cpc                        NaN   
4  3000721821736270436  ...                  cpc                        NaN   

  trafficSource_source       visitId visitNumber visitStartTime  \
0             (direct)  1.506841e+09         1.0   1.506841e+09   
1               google  1.506841e+09         1.0   1.506841e+09   
2               google  1.506841e+09         1.0   1.506841e+09   
3               google  1.506841e+09         1.0   1.506841e+09   
4               google  1.506841e+09         1.0   1.506841e+09   

  order_euros_complete  org_search chrome purchase  
0                616.0           0      1        1  
1                  0.0           0      1        0  
2                  0.0           0      1        0  
3                980.0           0      0        1  
4                497.0           0      0        1  

[5 rows x 84 columns]

In [245]:
data['predicted_purchase_LR'] = clf_lr.predict(data[features])

In [246]:
data.head()

Unnamed: 0 affiliate channelGrouping cpc        date    device_browser  \
0         0.0         0        Referral   0  20171001.0            Chrome   
1         1.0         0     Paid Search   1  20171001.0            Chrome   
2         2.0         0         Display   1  20171001.0            Chrome   
3         3.0         0         Display   1  20171001.0  Samsung Internet   
4         4.0         0         Display   1  20171001.0            Safari   

  device_deviceCategory device_isMobile device_operatingSystem  \
0               desktop           False              Macintosh   
1               desktop           False              Macintosh   
2                mobile            True                Android   
3                mobile            True                Android   
4                mobile            True                    iOS   

         fullVisitorId  ... trafficSource_referralPath trafficSource_source  \
0  9460190543836614586  ...                          /             (direct)   
1  1480173241963500874  ...                        NaN               google   
2  2873420789599649821  ...                        NaN               google   
3   958777956895332252  ...                        NaN               google   
4  3000721821736270436  ...                        NaN               google   

        visitId visitNumber visitStartTime order_euros_complete org_search  \
0  1.506841e+09         1.0   1.506841e+09                616.0          0   
1  1.506841e+09         1.0   1.506841e+09                  0.0          0   
2  1.506841e+09         1.0   1.506841e+09                  0.0          0   
3  1.506841e+09         1.0   1.506841e+09                980.0          0   
4  1.506841e+09         1.0   1.506841e+09                497.0          0   

   chrome purchase predicted_purchase_LR  
0       1        1                     1  
1       1        0                     1  
2       1        0                     1  
3       0        1                     1  
4       0        1                     1  

[5 rows x 85 columns]

In [247]:
data.groupby('purchase')['predicted_purchase_LR'].value_counts()

purchase  predicted_purchase_LR
0         1                        15870
          0                         7625
1         1                        21295
          0                         7520
Name: predicted_purchase_LR, dtype: int64

In [248]:
from sklearn.naive_bayes import GaussianNB

In [249]:
clf_NB = GaussianNB()

In [250]:
clf_NB.fit(data[features], data['purchase'])

GaussianNB()

In [251]:
data['predicted_purchase_NB'] = clf_NB.predict(data[features])

In [252]:
data.head()

Unnamed: 0 affiliate channelGrouping cpc        date    device_browser  \
0         0.0         0        Referral   0  20171001.0            Chrome   
1         1.0         0     Paid Search   1  20171001.0            Chrome   
2         2.0         0         Display   1  20171001.0            Chrome   
3         3.0         0         Display   1  20171001.0  Samsung Internet   
4         4.0         0         Display   1  20171001.0            Safari   

  device_deviceCategory device_isMobile device_operatingSystem  \
0               desktop           False              Macintosh   
1               desktop           False              Macintosh   
2                mobile            True                Android   
3                mobile            True                Android   
4                mobile            True                    iOS   

         fullVisitorId  ... trafficSource_source       visitId visitNumber  \
0  9460190543836614586  ...             (direct)  1.506841e+09         1.0   
1  1480173241963500874  ...               google  1.506841e+09         1.0   
2  2873420789599649821  ...               google  1.506841e+09         1.0   
3   958777956895332252  ...               google  1.506841e+09         1.0   
4  3000721821736270436  ...               google  1.506841e+09         1.0   

  visitStartTime order_euros_complete org_search chrome  purchase  \
0   1.506841e+09                616.0          0      1         1   
1   1.506841e+09                  0.0          0      1         0   
2   1.506841e+09                  0.0          0      1         0   
3   1.506841e+09                980.0          0      0         1   
4   1.506841e+09                497.0          0      0         1   

  predicted_purchase_LR predicted_purchase_NB  
0                     1                     1  
1                     1                     1  
2                     1                     1  
3                     1                     1  
4                     1                     1  

[5 rows x 86 columns]

In [253]:
data.groupby('purchase')['predicted_purchase_NB'].value_counts()

purchase  predicted_purchase_NB
0         1                        15870
          0                         7625
1         1                        21295
          0                         7520
Name: predicted_purchase_NB, dtype: int64

In [254]:
from sklearn.neighbors import KNeighborsClassifier

In [255]:
clf_KNN = KNeighborsClassifier(n_neighbors=3)

In [256]:
clf_KNN.fit(data[features], data['purchase'])

KNeighborsClassifier(n_neighbors=3)

In [257]:
data['predicted_purchase_KNN'] = clf_KNN.predict(data[features])

In [258]:
data.groupby('purchase')['predicted_purchase_KNN'].value_counts()

purchase  predicted_purchase_KNN
0         1                         19675
          0                          3820
1         1                         24999
          0                          3816
Name: predicted_purchase_KNN, dtype: int64

* Training set ~ 80% (if you only have a test set) or 60% (if you also have a validation set)
* Test set 20%
* Validation set (if available) 20%

In [259]:
from sklearn.model_selection import train_test_split

In [260]:
train, test = train_test_split(data, test_size=0.2, random_state=42)

In [261]:
train.head()

Unnamed: 0 affiliate channelGrouping cpc        date device_browser  \
12044     12044.0         0         Display   1  20171004.0         Chrome   
32928     32927.0         0        Referral   0  20171009.0         Chrome   
46083     46082.0         0          Social   0  20171013.0         Chrome   
51064     51062.0         0  Organic Search   0  20171015.0         Chrome   
25127     25127.0         0        Referral   0  20171007.0         Chrome   

      device_deviceCategory device_isMobile device_operatingSystem  \
12044                mobile            True                Android   
32928               desktop           False                  Linux   
46083               desktop           False                Windows   
51064               desktop           False                  Linux   
25127               desktop           False                Windows   

             fullVisitorId  ...       visitId visitNumber visitStartTime  \
12044   399270061740611406  ...  1.507139e+09         2.0   1.507139e+09   
32928  2283180547029955203  ...  1.507573e+09         1.0   1.507573e+09   
46083  7946255075327832830  ...  1.507909e+09         1.0   1.507909e+09   
51064  7096084199090126291  ...  1.508088e+09         1.0   1.508088e+09   
25127          7.67655e+18  ...  1.507392e+09         1.0   1.507392e+09   

      order_euros_complete org_search chrome purchase  predicted_purchase_LR  \
12044                971.0          0      1        1                      1   
32928                  0.0          0      1        0                      1   
46083                  0.0          0      1        0                      1   
51064                182.0          1      1        1                      0   
25127                  0.0          0      1        0                      1   

      predicted_purchase_NB predicted_purchase_KNN  
12044                     1                      1  
32928                     1                      1  
46083                     1                      1  
51064                     0                      1  
25127                     1                      1  

[5 rows x 87 columns]

In [262]:
test.head()

Unnamed: 0 affiliate channelGrouping cpc        date device_browser  \
36548     36547.0         0  Organic Search   0  20171010.0         Chrome   
26376     26376.0         0         Display   1  20171007.0         Chrome   
21940     21940.0         0  Organic Search   0  20171006.0         Chrome   
8907       8907.0         0  Organic Search   0  20171003.0         Chrome   
36441     36440.0         0  Organic Search   0  20171010.0         Chrome   

      device_deviceCategory device_isMobile device_operatingSystem  \
36548               desktop           False              Macintosh   
26376                mobile            True                Android   
21940               desktop           False              Macintosh   
8907                 mobile            True                Android   
36441               desktop           False                Windows   

             fullVisitorId  ...       visitId visitNumber visitStartTime  \
36548   457810557350214392  ...  1.507651e+09         1.0   1.507651e+09   
26376          1.12241e+18  ...  1.507419e+09         1.0   1.507419e+09   
21940  5963631948501878610  ...  1.507316e+09         1.0   1.507316e+09   
8907    233830236249633791  ...  1.507068e+09         1.0   1.507068e+09   
36441    24264360175766929  ...  1.507649e+09         1.0   1.507649e+09   

      order_euros_complete org_search chrome purchase  predicted_purchase_LR  \
36548                132.0          1      1        1                      0   
26376                  0.0          0      1        0                      1   
21940                154.0          1      1        1                      0   
8907                   0.0          1      1        0                      0   
36441                  1.0          1      1        1                      0   

      predicted_purchase_NB predicted_purchase_KNN  
36548                     0                      1  
26376                     1                      1  
21940                     0                      1  
8907                      0                      1  
36441                     0                      1  

[5 rows x 87 columns]

In [263]:
len(train), len(test), len(train)+len(test), len(data)

(41848, 10462, 52310, 52310)

In [264]:
clf_lr_test = LogisticRegression(random_state=0)

In [265]:
clf_lr_test.fit(train[features], train['purchase'])

LogisticRegression(random_state=0)

In [266]:
test['predicted_purchase_LR_test'] = clf_lr_test.predict(test[features])

<ipython-input-266-e8986de81e8a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['predicted_purchase_LR_test'] = clf_lr_test.predict(test[features])


In [267]:
clf_KNN_test = KNeighborsClassifier(n_neighbors=3)

In [268]:
clf_KNN_test.fit(train[features], train['purchase'])

KNeighborsClassifier(n_neighbors=3)

In [269]:
test['predicted_purchase_KNN_test'] = clf_KNN.predict(test[features])

<ipython-input-269-46243d428576>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['predicted_purchase_KNN_test'] = clf_KNN.predict(test[features])


In [270]:
test.head()

Unnamed: 0 affiliate channelGrouping cpc        date device_browser  \
36548     36547.0         0  Organic Search   0  20171010.0         Chrome   
26376     26376.0         0         Display   1  20171007.0         Chrome   
21940     21940.0         0  Organic Search   0  20171006.0         Chrome   
8907       8907.0         0  Organic Search   0  20171003.0         Chrome   
36441     36440.0         0  Organic Search   0  20171010.0         Chrome   

      device_deviceCategory device_isMobile device_operatingSystem  \
36548               desktop           False              Macintosh   
26376                mobile            True                Android   
21940               desktop           False              Macintosh   
8907                 mobile            True                Android   
36441               desktop           False                Windows   

             fullVisitorId  ... visitStartTime order_euros_complete  \
36548   457810557350214392  ...   1.507651e+09                132.0   
26376          1.12241e+18  ...   1.507419e+09                  0.0   
21940  5963631948501878610  ...   1.507316e+09                154.0   
8907    233830236249633791  ...   1.507068e+09                  0.0   
36441    24264360175766929  ...   1.507649e+09                  1.0   

      org_search chrome purchase predicted_purchase_LR predicted_purchase_NB  \
36548          1      1        1                     0                     0   
26376          0      1        0                     1                     1   
21940          1      1        1                     0                     0   
8907           1      1        0                     0                     0   
36441          1      1        1                     0                     0   

       predicted_purchase_KNN predicted_purchase_LR_test  \
36548                       1                          0   
26376                       1                          1   
21940                       1                          0   
8907                        1                          0   
36441                       1                          0   

      predicted_purchase_KNN_test  
36548                           1  
26376                           1  
21940                           1  
8907                            1  
36441                           1  

[5 rows x 89 columns]

In [271]:
test.groupby('purchase')['predicted_purchase_KNN_test'].value_counts()

purchase  predicted_purchase_KNN_test
0         1                              3978
          0                               731
1         1                              4959
          0                               794
Name: predicted_purchase_KNN_test, dtype: int64

In [272]:
from sklearn.metrics import confusion_matrix

In [273]:
print(confusion_matrix(test['purchase'], test['predicted_purchase_LR_test']))

[[1565 3144]
 [1471 4282]]


In [274]:
print(confusion_matrix(test['purchase'], test['predicted_purchase_KNN_test']))

[[ 731 3978]
 [ 794 4959]]


In [275]:
from sklearn.metrics import classification_report

In [276]:
print(classification_report(test['purchase'], test['predicted_purchase_LR_test']))

              precision    recall  f1-score   support

           0       0.52      0.33      0.40      4709
           1       0.58      0.74      0.65      5753

    accuracy                           0.56     10462
   macro avg       0.55      0.54      0.53     10462
weighted avg       0.55      0.56      0.54     10462



In [277]:
print(classification_report(test['purchase'], test['predicted_purchase_KNN_test']))

              precision    recall  f1-score   support

           0       0.48      0.16      0.23      4709
           1       0.55      0.86      0.68      5753

    accuracy                           0.54     10462
   macro avg       0.52      0.51      0.45     10462
weighted avg       0.52      0.54      0.48     10462



In [278]:
clf_KNN_test10 = KNeighborsClassifier(n_neighbors=10)

In [279]:
clf_KNN_test10.fit(train[features], train['purchase'])

KNeighborsClassifier(n_neighbors=10)

In [280]:
test['predicted_purchase_KNN_test10'] = clf_KNN_test10.predict(test[features])

<ipython-input-280-83545588bcb0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['predicted_purchase_KNN_test10'] = clf_KNN_test10.predict(test[features])


In [281]:
print(classification_report(test['purchase'], test['predicted_purchase_KNN_test10']))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      4709
           1       0.55      1.00      0.71      5753

    accuracy                           0.55     10462
   macro avg       0.27      0.50      0.35     10462
weighted avg       0.30      0.55      0.39     10462



/Users/t.b.araujouva.nl/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
