In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
def create_data(IV):
    return IV * 2 + (np.random.randint(0,10))/10

In [4]:
create_data(1)

2.0

In [6]:
create_data(25)

50.4

In [7]:
df = []

In [8]:
counter = 0
while counter < 1000:
    value = {}
    value['IV'] = np.random.randint(0,100)
    df.append(value)
    counter += 1

In [9]:
df[:10]

[{'IV': 72},
 {'IV': 80},
 {'IV': 47},
 {'IV': 49},
 {'IV': 39},
 {'IV': 16},
 {'IV': 25},
 {'IV': 26},
 {'IV': 67},
 {'IV': 67}]

In [10]:
df = pd.DataFrame(df)

In [11]:
df

IV
0    72
1    80
2    47
3    49
4    39
..   ..
995  57
996  57
997  38
998  32
999  68

[1000 rows x 1 columns]

In [12]:
df.describe()

IV
count  1000.000000
mean     48.264000
std      28.046406
min       0.000000
25%      25.000000
50%      47.000000
75%      72.000000
max      99.000000

In [13]:
df['DV'] = df['IV'].apply(create_data)

In [14]:
df

IV     DV
0    72  144.1
1    80  160.9
2    47   94.0
3    49   98.2
4    39   78.2
..   ..    ...
995  57  114.6
996  57  114.1
997  38   76.1
998  32   64.8
999  68  136.2

[1000 rows x 2 columns]

In [15]:
df.describe()

IV           DV
count  1000.000000  1000.000000
mean     48.264000    96.975700
std      28.046406    56.101059
min       0.000000     0.000000
25%      25.000000    50.275000
50%      47.000000    94.050000
75%      72.000000   144.625000
max      99.000000   198.800000

## Using sklearn to train a model and make predictions

In [16]:
from sklearn.linear_model import LinearRegression

Instantiating the model

In [17]:
reg = LinearRegression()

In [18]:
reg

LinearRegression()

Fitting the model with training data

In [27]:
reg.fit(df[['IV']], df['DV'])

LinearRegression()

In [25]:
df[['IV']]

IV
0    72
1    80
2    47
3    49
4    39
..   ..
995  57
996  57
997  38
998  32
999  68

[1000 rows x 1 columns]

In [26]:
df['DV']

0      144.1
1      160.9
2       94.0
3       98.2
4       78.2
       ...  
995    114.6
996    114.1
997     76.1
998     64.8
999    136.2
Name: DV, Length: 1000, dtype: float64

In [29]:
reg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

Getting the coefficient(s)

In [30]:
reg.coef_

array([2.00026763])

Making predictions

In [34]:
reg.predict([[1]])

array([2.43505075])

In [35]:
reg.predict([[100]])

array([200.46154609])

In [36]:
reg.predict([[50]])

array([100.44816461])

In [37]:
df['IV'].max()

99

In [38]:
reg.predict([[1000]])

array([2000.70241276])

## Statistical testing

In [39]:
import statsmodels.api as sm

In [40]:
Y = df['DV']
X = df['IV']

In [41]:
X = sm.add_constant(X)

In [42]:
model = sm.OLS(Y,X)

In [43]:
results = model.fit()

In [44]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     DV   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.780e+07
Date:                Fri, 02 Jul 2021   Prob (F-statistic):               0.00
Time:                        11:29:41   Log-Likelihood:                -174.59
No. Observations:                1000   AIC:                             353.2
Df Residuals:                     998   BIC:                             363.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4348      0.018     23.942      0.000       0.399       0.470
IV             2.0003      0.000   6147.890      0.000       2.000       2.001
==============================================================================
Omnibus:                      926.121   Durbin-Watson:                   2.108
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               62.830
Skew:                           0.021   Prob(JB):                     2.27e-14
Kurtosis:                       1.773   Cond. No.                         111.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Using the Google Analytics Dataset
(Modified for Digital Analytics)

In [45]:
data = pd.read_csv('/Users/t.b.araujouva.nl/OneDrive - UvA/DigitalSociety/TeachTheTeacher-Python/TeachTheTeacherPython-Datasets/googlestore_DA5weeklychallenges.csv')

/Users/t.b.araujouva.nl/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (1,3,7,9,19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [46]:
data.head()

Unnamed: 0 affiliate channelGrouping cpc        date    device_browser  \
0         0.0         0        Referral   0  20171001.0            Chrome   
1         1.0         0     Paid Search   1  20171001.0            Chrome   
2         2.0         0         Display   1  20171001.0            Chrome   
3         3.0         0         Display   1  20171001.0  Samsung Internet   
4         4.0         0         Display   1  20171001.0            Safari   

  device_deviceCategory device_isMobile device_operatingSystem  \
0               desktop           False              Macintosh   
1               desktop           False              Macintosh   
2                mobile            True                Android   
3                mobile            True                Android   
4                mobile            True                    iOS   

         fullVisitorId  ... trafficSource_adwordsClickInfo_slot  \
0  9460190543836614586  ...                                 NaN   
1  1480173241963500874  ...                                 Top   
2  2873420789599649821  ...                                 RHS   
3   958777956895332252  ...                                 RHS   
4  3000721821736270436  ...                                 RHS   

                              trafficSource_campaign  \
0                                          (not set)   
1                 AW - Dynamic Search Ads Whole Site   
2  1000557 | GA | US | en | Hybrid | GDN Remarketing   
3  1000557 | GA | US | en | Hybrid | GDN Remarketing   
4  1000557 | GA | US | en | Hybrid | GDN Remarketing   

  trafficSource_isTrueDirect trafficSource_keyword trafficSource_medium  \
0                        NaN                   NaN               (none)   
1                        NaN      6qEhsCssdK0z36ri                  cpc   
2                        NaN  (automatic matching)                  cpc   
3                        NaN  (automatic matching)                  cpc   
4                        NaN  (automatic matching)                  cpc   

  trafficSource_referralPath trafficSource_source       visitId visitNumber  \
0                          /             (direct)  1.506841e+09         1.0   
1                        NaN               google  1.506841e+09         1.0   
2                        NaN               google  1.506841e+09         1.0   
3                        NaN               google  1.506841e+09         1.0   
4                        NaN               google  1.506841e+09         1.0   

  visitStartTime  
0   1.506841e+09  
1   1.506841e+09  
2   1.506841e+09  
3   1.506841e+09  
4   1.506841e+09  

[5 rows x 80 columns]

In [47]:
data.columns

Index(['Unnamed: 0', 'affiliate', 'channelGrouping', 'cpc', 'date',
       'device_browser', 'device_deviceCategory', 'device_isMobile',
       'device_operatingSystem', 'fullVisitorId', 'geoNetwork_city',
       'geoNetwork_continent', 'geoNetwork_country', 'geoNetwork_metro',
       'geoNetwork_networkDomain', 'geoNetwork_region',
       'geoNetwork_subContinent', 'isExit',
       'landing_appInfo_landingScreenName', 'landing_appInfo_screenDepth',
       'landing_appInfo_screenName', 'landing_contentGroup_contentGroup1',
       'landing_contentGroup_contentGroup2',
       'landing_contentGroup_contentGroup3',
       'landing_contentGroup_contentGroup4',
       'landing_contentGroup_contentGroup5', 'landing_hour',
       'landing_isEntrance', 'landing_isExit', 'landing_minute',
       'landing_page_hostname', 'landing_page_pagePath',
       'landing_page_pagePathLevel1', 'landing_page_pagePathLevel2',
       'landing_page_pagePathLevel3', 'landing_page_pagePathLevel4',
       'landing

In [48]:
data['order_euros']

0        616.0
1          NaN
2          NaN
3        980.0
4        497.0
         ...  
52305    977.0
52306    240.0
52307    764.0
52308      NaN
52309    990.0
Name: order_euros, Length: 52310, dtype: float64

In [49]:
data[['channelGrouping', 'device_browser', 'order_euros']].describe()

order_euros
count  28815.000000
mean     412.265279
std      312.846197
min        1.000000
25%      131.000000
50%      336.000000
75%      691.000000
max      999.000000

In [50]:
data[['channelGrouping', 'device_browser', 'order_euros']].dtypes

channelGrouping     object
device_browser      object
order_euros        float64
dtype: object

In [51]:
data[['channelGrouping', 'device_browser', 'order_euros']].isna().sum()

channelGrouping        0
device_browser         0
order_euros        23495
dtype: int64

In [52]:
data['channelGrouping'].value_counts()

Organic Search    22781
Display           12579
Direct             6047
Referral           4994
Social             3828
Paid Search        1322
Affiliates          756
 :                    2
(Other)               1
Name: channelGrouping, dtype: int64

In [53]:
data['device_browser'].value_counts()

Chrome                        34324
Safari                         8883
Samsung Internet               3100
Android Webview                1783
Firefox                        1693
Internet Explorer               780
Opera Mini                      484
Edge                            432
Opera                           261
UC Browser                      220
Safari (in-app)                 141
Amazon Silk                      71
YaBrowser                        37
Android Browser                  35
Coc Coc                          15
Puffin                           13
Mozilla Compatible Agent         10
BlackBerry                        7
Maxthon                           7
1                                 2
osee2unifiedRelease               2
tfowdqmibyshaklxuregpcnzvj        1
ujvrzsonxihlgaqdmkwtbfcpey        1
wfpknuqxovyilmrdzbhgtecjas        1
(not set)                         1
Browser                           1
ecgiwapzltrkujdhmqsbxfonvy        1
Nintendo Browser            

In [54]:
data['order_euros'].describe()

count    28815.000000
mean       412.265279
std        312.846197
min          1.000000
25%        131.000000
50%        336.000000
75%        691.000000
max        999.000000
Name: order_euros, dtype: float64

In [55]:
data['order_euros_complete'] = data['order_euros'].fillna(0)

In [56]:
data['order_euros_complete'].describe()

count    52310.000000
mean       227.096616
std        309.781227
min          0.000000
25%          0.000000
50%         42.000000
75%        391.000000
max        999.000000
Name: order_euros_complete, dtype: float64

In [57]:
data['order_euros_complete'].isna().sum()

0

In [58]:
def is_organic_search(text):
    if text == 'Organic Search':
        return 1
    return 0

In [59]:
data['org_search'] = data['channelGrouping'].apply(is_organic_search)

In [60]:
data['org_search'].value_counts()

0    29529
1    22781
Name: org_search, dtype: int64

In [61]:
def is_chrome(text):
    if 'Chrome' in text:
        return 1
    else:
        return 0

In [63]:
data['chrome'] = data['device_browser'].apply(is_chrome)

In [64]:
data['chrome'].value_counts()

1    34324
0    17986
Name: chrome, dtype: int64

In [69]:
data['chrome']

0        1
1        1
2        1
3        0
4        0
        ..
52305    1
52306    1
52307    1
52308    1
52309    0
Name: chrome, Length: 52310, dtype: int64

In [70]:
data[['chrome', 'org_search', 'order_euros_complete']]

chrome  org_search  order_euros_complete
0           1           0                 616.0
1           1           0                   0.0
2           1           0                   0.0
3           0           0                 980.0
4           0           0                 497.0
...       ...         ...                   ...
52305       1           0                 977.0
52306       1           1                 240.0
52307       1           0                 764.0
52308       1           1                   0.0
52309       0           0                 990.0

[52310 rows x 3 columns]

In [71]:
data[['chrome', 'org_search', 'order_euros_complete']].describe()

chrome    org_search  order_euros_complete
count  52310.000000  52310.000000          52310.000000
mean       0.656165      0.435500            227.096616
std        0.474991      0.495827            309.781227
min        0.000000      0.000000              0.000000
25%        0.000000      0.000000              0.000000
50%        1.000000      0.000000             42.000000
75%        1.000000      1.000000            391.000000
max        1.000000      1.000000            999.000000

In [72]:
data[['chrome', 'org_search', 'order_euros_complete']].isna().sum()

chrome                  0
org_search              0
order_euros_complete    0
dtype: int64

In [73]:
features = ['chrome', 'org_search']

In [74]:
features

['chrome', 'org_search']

In [75]:
import statsmodels.api as sm

In [76]:
X = sm.add_constant(data[features])

In [77]:
model_euros = sm.OLS(data['order_euros_complete'], X)

In [78]:
results_model_euros = model_euros.fit()

In [79]:
results_model_euros.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results                             
================================================================================
Dep. Variable:     order_euros_complete   R-squared:                       0.133
Model:                              OLS   Adj. R-squared:                  0.133
Method:                   Least Squares   F-statistic:                     4023.
Date:                  Fri, 02 Jul 2021   Prob (F-statistic):               0.00
Time:                          12:03:05   Log-Likelihood:            -3.7052e+05
No. Observations:                 52310   AIC:                         7.411e+05
Df Residuals:                     52307   BIC:                         7.411e+05
Df Model:                             2                                         
Covariance Type:              nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        349.1769      2.406    145.108      0.000     344.461     353.893
chrome       -36.8375      2.655    -13.874      0.000     -42.041     -31.634
org_search  -224.8195      2.543    -88.390      0.000    -229.805    -219.834
==============================================================================
Omnibus:                     4605.359   Durbin-Watson:                   1.967
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5183.579
Skew:                           0.736   Prob(JB):                         0.00
Kurtosis:                       2.542   Cond. No.                         3.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [80]:
from sklearn.linear_model import LinearRegression

In [81]:
reg_order_euros = LinearRegression()

In [82]:
reg_order_euros.fit(data[features], data['order_euros_complete'])

LinearRegression()

In [83]:
reg_order_euros.coef_

array([ -36.83747443, -224.81947091])

In [84]:
reg_order_euros.predict([[1,1]])

array([87.51999672])

In [85]:
reg_order_euros.predict([[0,0]])

array([349.17694206])

In [86]:
reg_order_euros.predict([[1,0]])

array([312.33946763])

In [87]:
reg_order_euros.predict([[0,1]])

array([124.35747115])